import { buildSections } from "./sections.js";
import { hashFiles } from "./hash.js";

// NB: HTML comments don't nest — the first "-->" closes the block. So this
// header must never contain a literal example of a handoverkit comment, or
// everything after it leaks out and renders as visible text in SERVICE.md.
const HEADER = `<!--
  This file is partially generated by handover-kit.
  Do not remove the "handoverkit:" HTML comments below each heading — they
  store a hash of the files each section was derived from, which is how
  \`handoverkit check\` knows a section has gone stale.
  Freely edit the prose; the hash only tracks the *source files*, not your
  edits to this document.
-->
`;

export async function generateServiceMd(repoRoot: string): Promise<string> {
  const sections = await buildSections(repoRoot);
  const blocks: string[] = [HEADER, "# Service Handover Doc\n"];

  for (const section of sections) {
    const content = await section.render();
    const hash = await hashFiles(repoRoot, section.sourceFiles);
    blocks.push(
      `## ${section.title}\n` +
        `<!-- handoverkit:id=${section.id} hash=${hash} sources=${section.sourceFiles.join(",")} -->\n` +
        `${content}\n`
    );
  }

  return blocks.join("\n");
}
