import { buildSections } from "./sections.js";
import { hashFiles } from "./hash.js";

const HEADER = `<!--
  This file is partially generated by handover-kit.
  Do not remove the <!-- handoverkit:... --> comments below each heading —
  they store a hash of the files each section was derived from, which is
  how \`handoverkit check\` knows a section has gone stale.
  Freely edit the prose; the hash only tracks the *source files*, not
  your edits to this document.
-->
`;

export async function generateServiceMd(repoRoot: string): Promise<string> {
  const sections = await buildSections(repoRoot);
  const blocks: string[] = [HEADER, "# Service Handover Doc\n"];

  for (const section of sections) {
    const content = await section.render();
    const hash = await hashFiles(repoRoot, section.sourceFiles);
    blocks.push(
      `## ${section.title}\n` +
        `<!-- handoverkit:id=${section.id} hash=${hash} sources=${section.sourceFiles.join(",")} -->\n` +
        `${content}\n`
    );
  }

  return blocks.join("\n");
}
